# Generated by Django 4.2.3 on 2023-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0002_auto_20230817_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeFamilleGrade',
            fields=[
                ('codfamgr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libfamgr', models.CharField(max_length=255)),
                ('echelle', models.IntegerField()),
                ('dateeffe', models.DateField()),
            ],
            options={
                'db_table': 'liste_famille_grade',
            },
        ),
        migrations.CreateModel(
            name='ListeGrade',
            fields=[
                ('codecate', models.IntegerField(primary_key=True, serialize=False)),
                ('libecate', models.CharField(max_length=255)),
                ('codecorp', models.IntegerField()),
                ('codecadr', models.IntegerField()),
                ('idengrad', models.IntegerField(default=0)),
                ('codegrad', models.IntegerField()),
                ('libegrad', models.CharField(max_length=255)),
                ('codecomp', models.IntegerField()),
                ('codfamgr', models.CharField(max_length=10)),
                ('echelle', models.IntegerField()),
                ('echelon', models.IntegerField()),
                ('poinindi', models.IntegerField()),
            ],
            options={
                'db_table': 'liste_grade',
            },
        ),
        migrations.CreateModel(
            name='RubDroitProfEnsSec2Gr',
            fields=[
                ('idendroi', models.IntegerField(primary_key=True, serialize=False)),
                ('idengrad', models.IntegerField()),
                ('coderubr', models.CharField(max_length=10)),
                ('libegrad', models.CharField(max_length=255)),
                ('liberubr', models.CharField(max_length=255)),
                ('naturubr', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rub_droit_prof_ens_sec_2_gr',
            },
        ),
        migrations.CreateModel(
            name='SitPaieProfEnsSec2Gr',
            fields=[
                ('idendroi', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('idengrad', models.IntegerField()),
                ('idencomb', models.IntegerField()),
                ('codfamgr', models.CharField(max_length=10)),
                ('echelon', models.IntegerField()),
                ('idendepa', models.IntegerField()),
                ('codezone', models.CharField(max_length=10)),
                ('coderubr', models.CharField(max_length=10)),
                ('liberubr', models.CharField(max_length=255)),
                ('montoctr', models.DecimalField(decimal_places=2, max_digits=15)),
                ('typeoctr', models.CharField(max_length=50)),
                ('perioctr', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sit_paie_prof_ens_sec_2_gr',
            },
        ),
        migrations.CreateModel(
            name='ListeGradeFamilleGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idengrad', models.IntegerField()),
                ('codfamgr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'liste_grade_famille_grade',
                'unique_together': {('idengrad', 'codfamgr')},
            },
        ),
    ]
