# Generated by Django 4.2.3 on 2023-08-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeurs', '0003_listefamillegrade_listegrade_rubdroitprofenssec2gr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubdroitprofenssec2gr',
            name='coderubr',
            field=models.CharField(db_collation='pg_catalog.default', max_length=255),
        ),
        migrations.AlterField(
            model_name='rubdroitprofenssec2gr',
            name='libegrad',
            field=models.CharField(db_collation='pg_catalog.default', max_length=255),
        ),
        migrations.AlterField(
            model_name='rubdroitprofenssec2gr',
            name='liberubr',
            field=models.CharField(db_collation='pg_catalog.default', max_length=255),
        ),
        migrations.AlterField(
            model_name='rubdroitprofenssec2gr',
            name='naturubr',
            field=models.CharField(db_collation='pg_catalog.default', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitpaieprofenssec2gr',
            name='coderubr',
            field=models.CharField(db_collation='pg_catalog.default', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitpaieprofenssec2gr',
            name='idendroi',
            field=models.CharField(db_collation='pg_catalog.default', max_length=255, primary_key=True, serialize=False),
        ),
    ]
